README.md

The project readme step "Add some seeds to your seeds.exs" causes an error when running `mix ecto.reset` as suggested:
```
** (CompileError) nofile:4: module BeaconWeb.LiveRenderer.Component6A217F0F7032720EB50A1A2FBF258463 is not loaded and could not be found
(elixir 1.13.4) lib/code.ex:1392: Code.compile_string/2
(beacon 0.1.0) lib/beacon/loader/module_loader.ex:6: Beacon.Loader.ModuleLoader.load/2
(beacon 0.1.0) lib/beacon/loader/layout_module_loader.ex:18: Beacon.Loader.LayoutModuleLoader.load_layouts/2
(beacon 0.1.0) lib/beacon/loader/db_loader.ex:32: anonymous fn/1 in Beacon.Loader.DBLoader.load_layouts/0
(elixir 1.13.4) lib/enum.ex:942: anonymous fn/3 in Enum.each/2
(stdlib 4.0) maps.erl:411: :maps.fold_1/3
(elixir 1.13.4) lib/enum.ex:2408: Enum.each/2
(beacon 0.1.0) …
```

Fix seeds.exs in readme

---

lib/beacon/loader/layout_module_loader.ex
lib/beacon/loader/module_loader.ex
lib/beacon/loader/page_module_loader.ex

This will first check if my_component is used before importing in order
to avoid runtime warnings.

Fix runtime warnings from my_component

---

README.md
config/config.exs
lib/beacon/loader.ex
lib/beacon/loader/component_module_loader.ex
lib/beacon/loader/db_loader.ex
lib/beacon/loader/layout_module_loader.ex
lib/beacon/loader/page_module_loader.ex
lib/beacon/pages.ex
lib/beacon/pages/page.ex
lib/beacon/pages/page_event.ex
lib/beacon_web/live/page_live.ex
priv/repo/migrations/20220823185841_create_beacon_page_events.exs
test/beacon_web/live/page_live_test.exs

Fixes #19.
This PR adds the concept of a `PageEvent`. Pages can have events, which for now define an event name and code. The code will have `event_params` and the `socket` in scope, and should return `{:noreply, socket}`.
See the seed in the README file walkthrough for an example.
Additional changes:
Safe Code is now disabled by default. Will re-enable once we have time to work on improving the SafeCode interaction.
Fix edge case with call_function_with_retry error handling.

Add events to pages

---

lib/beacon_web/live/page_management/page_live/form_component.html.heex
lib/beacon_web/live/page_management/page_live/index.html.heex
lib/beacon_web/live/page_management/page_live/page_editor_live.html.heex

Shouldn't need to use "back" buttons

Add cancel links to page manager forms

---

mix.exs

Too strict will block apps to install beacon.

Loosen dependencies requirements

---

CONTRIBUTING.md
README.md
config/config.exs
dev.exs
lib/beacon/router.ex
lib/beacon_web/beacon_web.ex
lib/beacon_web/components/layouts.ex
lib/beacon_web/live/page_management/page_live/index.html.heex
lib/beacon_web/live/page_management/page_live/page_editor_live.html.heex
mix.exs
priv/assets/tailwind.config.js
priv/assets/tailwind.config.js.eex
test/beacon/router_test.exs
test/support/router.ex

Allow users to run admin on custom path and close https://github.com/BeaconCMS/beacon/pull/33. This one is extracted from https://github.com/BeaconCMS/beacon/pull/86 to keep the Asset Manager PR smaller.
Also close #105 which is related.

Introduce `live_admin_path` to generate router paths on Admin

---

lib/beacon_web/components/layouts.ex
lib/beacon_web/components/layouts/runtime.html.heex
lib/beacon_web/live/page_live.ex

Following on from adding page meta tags, I renamed the layout meta tags functions from e.g. `meta_tags` to `layout_meta_tags`. Think I got everything, let me know if I missed something.

Prefix layout meta tag fns with "layout_"

---

guides/introduction/installation.md
lib/mix/tasks/install.ex

Updates the installation mix task so that beacon's seeds are run on `mix setup`.

Inject beacon seeds into ecto.setup alias

---

lib/beacon/css_compiler.ex
lib/beacon/loader/component_module_loader.ex
lib/beacon/loader/layout_module_loader.ex
lib/beacon/loader/page_module_loader.ex
lib/beacon/loader/stylesheet_module_loader.ex
lib/beacon/pub_sub.ex
lib/beacon/runtime_css.ex

The tailwind-cli fails to parse some special chars in the raw content and escaping doesn't work either. Just removing them for now to get it working.
```
** (Mix) Could not start application beacon: Beacon.Application.start(:normal, []) returned an error: shutdown: failed to start child: Beacon.Loader.Server
** (EXIT) an exception was raised:
** (RuntimeError) Error running tailwind with exit code 1
(beacon 0.1.0-dev) lib/beacon/css_compiler.ex:41: Beacon.CSSCompiler.compile!/2
(beacon 0.1.0-dev) lib/beacon/loader/layout_module_loader.ex:32: Beacon.Loader.LayoutModuleLoader.render_layout/1
(elixir 1.14.2) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
(beacon 0.1.0-dev) lib/beacon/loader/layout_module_loader.ex:11: Beacon.Loader.LayoutModuleLoader.load_layouts/2
(beacon 0.1.0-dev) …
```

Prevent tailwind-cli parser fail

---

lib/beacon/loader/stylesheet_module_loader.ex
lib/beacon/tailwind_compiler.ex
lib/beacon_web/components/layouts.ex
lib/beacon_web/components/layouts/runtime.html.heex
priv/beacon_tailwind.css
test/beacon_web/live/page_live_test.exs

We need to import the app css into the input source to evaluate tailwind functions and directives https://tailwindcss.com/docs/functions-and-directives.
Another option would be using PostCSS on the host application but I don't think asking users to do it is good UX if we can provide basic import out of the box.

Import app css

---

lib/beacon/layouts.ex
lib/beacon_web/live/admin/page_live/form_component.ex
lib/beacon_web/live/admin/page_live/form_component.html.heex
test/beacon/layouts_test.exs

I get the following error after going to the `http://localhost:4000/admin/pages/new` route (after running the project for the first time)
```elixir
** (ArgumentError) comparison with nil is forbidden as it is unsafe. If you want to check if a value is nil, use is_nil/1 instead
(ecto 3.9.4) lib/ecto/query/builder.ex:1045: Ecto.Query.Builder.not_nil!/1
(beacon 0.1.0-dev) lib/beacon/layouts.ex:27: Beacon.Layouts.list_layouts_for_site/1
(beacon 0.1.0-dev) lib/beacon_web/live/admin/page_live/form_component.ex:75: BeaconWeb.Admin.PageLive.FormComponent.assign_layouts/1
```
This problem is happening because we tried to load a list of **Layouts** based on a **site**, but at this moment we still don't know which **site** to use, so we call `Layouts.list_layouts_for_site(nil)` and the error above …

Fix query error: comparison with nil is forbidden - /admin/pages/new

---

dev.exs
guides/introduction/admin.md
guides/introduction/api.md
guides/introduction/installation.md
lib/beacon/beacon_attrs.ex
lib/beacon/loader.ex
lib/beacon/loader/component_module_loader.ex
lib/beacon/loader/layout_module_loader.ex
lib/beacon/loader/page_module_loader.ex
lib/beacon/router.ex
lib/beacon_web/components/layouts.ex
lib/beacon_web/live/page_live.ex
priv/templates/install/beacon_router_scope.ex
test/beacon/router_test.exs
test/beacon_web/controllers/media_library_controller_test.exs
test/mix/tasks/install_test.exs
test/support/router.ex

Support TagEngine from PhoenixLiveView 0.18.17 and misc improvements

---

lib/beacon/router.ex
test/beacon/router_test.exs

Admin routes for a beacon site.
defmodule MyAppWeb.Router do
use Phoenix.Router
use Beacon.Router
scope "/", MyAppWeb do
pipe_through :browser
beacon_admin "/admin", on_mount: [SomeHook]
end
end
* `:on_mount` (optional) , an optional list of `on_mount` hooks passed to `live_session`.
This will allow for authenticated routes, among other uses.

allow beacon_admin to accept opts to configure live_session.

---

dev.exs
lib/beacon/beacon_attrs.ex
lib/beacon_web/components/components.ex
lib/beacon_web/live/page_live.ex

It adds a bit of complexity on our side because the proc dict isn't so explicit but on the other hand improves the UX for the final user who shouldn't be aware of `@beacon_attrs` to call built-in components.

Leverage the process dict to avoid requiring attr beacon_attrs

---

lib/beacon_web/admin/hooks/assign_agent.ex
test/beacon/authorization_test.exs
test/beacon_web/hooks/assign_agent_test.exs
test/beacon_web/live/admin/page_live/index_test.exs
test/support/beacon_authorization_source.ex

Changes `get_agent` parameter semantics.
AssignAgent originally pulled data from the session under the key, `authorization_bootstrap` and passed that to `get_agent`. This put an unnecessary burden and constraint upon the implementor. We now simply pass in the session blindly to `get_agent` and allow the implementor to do what they want with that data. In the course of refactoring this, I had to change atom key references to string to match session keys.

remove authorization_bootstrap

---

dev.exs
lib/beacon/config.ex
lib/beacon/lifecycle.ex
lib/beacon/page_field.ex
lib/beacon/pages.ex
lib/beacon/pages/page.ex
lib/beacon_web/live/admin/page_live/page_editor_live.ex
lib/beacon_web/live/admin/page_live/page_editor_live.html.heex
priv/repo/migrations/20230418141354_add_extra_to_pages.exs
test/beacon/config_test.exs
test/beacon/page_field_test.exs
test/beacon/pages_test.exs
test/support/fixtures.ex
test/support/page_fields.ex
test/test_helper.exs

`Beacon.Pages.Page` has a limited set of fields, the minimum required for a page to work. Any other field needed by host apps, for eg `tags`, `author`, and so on, are considered "extra, ie: they don't belong to beacon core but users should be able to store and manage such fields on Beacon Admin.
This PR introduces:
- a `jsonb` column to store such fields, which doesn't require migrations
- a behaviour to define the template to be displayed on page editor form (admin) and the changeset to validate those fields
https://github.com/BeaconCMS/beacon/blob/2a892b749cef379fa503597910ea97764a593ff1/dev.exs#L97-L123

Introduce Extra Page Fields

---

lib/beacon/admin/media_library.ex
lib/beacon/admin/media_library/asset.ex
lib/beacon/admin/media_library/backend.ex
lib/beacon/admin/media_library/backend/repo.ex
lib/beacon/admin/media_library/upload_metadata.ex
lib/beacon/config.ex
lib/beacon/lifecycle/asset.ex
lib/beacon_web/live/admin/media_library_live/upload_form_component.ex
test/beacon/admin/media_library_test.exs
test/beacon/config_test.exs
test/beacon/lifecycle/asset_test.exs
test/beacon_web/live/admin/media_library_live/upload_form_component_test.exs
test/support/fixtures.ex
test/test_helper.exs

Added resource key to UploadMetadata to hold changeset
Refactor the Backend API, relies solely on UploadMetadata, changed some naming.
Refactor Beacon.Admin.MediaLibrary.upload, split it into multiple functions for re-use by Lifecycle
Added :upload_asset key to Lifecycle.t()

introduce upload asset lifecycle

---

lib/beacon_web/live/admin/page_live/meta_tags_inputs.ex

When there are more than 10 meta tags on a page, editing the meta tags will cause the fields to re-render in a different order. This is very disorienting and makes it impossible to update meta tags.
Fields are stored in assigns with their index, starting at 0, and sorted using erlang term ordering.  However, the number is a String type.  Therefore the ordering is fine for single digits (0 to 9) but when the 11th field (index 10) is added, sorting becomes "0", "1", "10", "2", "3", etc...
`Enum.sort_by(..., &String.to_integer/1)`

Fix meta tag ordering issue

---

lib/beacon/pages/page.ex

Most pages added so far are markdown, so we have a request to change the default to that instead of heex.
Eventually we can allow this default to be configured for each site, but it's currently a complicated implementation due to how beacon admin handles site selection.  It's probably best to wait until that functionality is improved before adding this into the site config.

Change default page format to markdown

---

lib/beacon/admin/media_library/backend.ex

Backends can be configured as a list of of modules or a list of {module, config} tuples.
The `Beacon.Admin.MediaLibrary.Backend` functions' params were broken with respect to the tuple implementation.
This was fixed by splitting the functions and pattern matching in the head of the function.

backend arity fix

---

lib/beacon/media_library/asset.ex
lib/beacon_web/cache.ex
lib/beacon_web/cache/stale.ex
lib/beacon_web/controllers/media_library_controller.ex

Grabbed code from:
https://github.com/hexpm/hexpm/
Allows us to etag any future schema and is aware of associations.
We could apply this page controllers, etc.

Add etag support for assets

---

.gitignore
docker-compose.yml
lib/beacon/content/layout.ex
test/beacon_web/live/page_live_test.exs

closes #150 
It turns out that the stylesheets were already optional as the changeset was configured.
An additional validation through either `validate_change` or a combination of `get_field`/`get_change` and `add_error` must be done if an array field is to be considered invalid on an empty list, but this is not a concern in any of the other schemas which I found in the code.

fix: remove requirement on :stylesheet_urls from Layout schema

---

lib/beacon/content.ex

due to some data migration some events ended up
with the same timestamp which was causing this
query to return the created event since it was
inserted before and causing the page to not get loaded

make sure we find published pages

---

config/config.exs
lib/beacon/admin/media_library.ex
lib/beacon/admin/media_library/asset.ex
lib/beacon/content.ex
lib/beacon/content/component.ex
lib/beacon/content/layout.ex
lib/beacon/content/layout_event.ex
lib/beacon/content/layout_snapshot.ex
lib/beacon/content/page.ex
lib/beacon/content/page_event.ex
lib/beacon/content/page_snapshot.ex
lib/beacon/content/snippets/helper.ex
lib/beacon/content/stylesheet.ex
lib/beacon/media_library/asset.ex
lib/beacon/schema.ex
priv/repo/migrations/20230630205632_convert_timestamps_to_utc_datetime_usec.exs
test/beacon/content_test.exs

- Make sure `Beacon.Content.list_published_pages/1` finds the published page when `inserted_at` is equal.
- And another related change is to use `utc_datetime_usec` by default for timestamps to avoid such order issues.
Using DateTime over NaiveDateTime since it makes more sense and adding usec because it may be useful.
- https://elixirforum.com/t/why-use-utc-datetime-over-naive-datetime-for-ecto/32532/4
- https://elixirforum.com/t/why-cant-timestamptz-be-set-up-as-default-timestamp-for-migrations-in-config/25778/2

Fix list_published_pages edge case and convert timestamps to utc_datetime_usec

---

dev.exs
guides/introduction/api.md
lib/beacon/blueprint_converter.ex
lib/beacon/plug.ex
lib/beacon_web/controllers/api/component_controller.ex
lib/beacon_web/controllers/api/component_json.ex
mix.exs
mix.lock

Closes #300
Internally elixir uses snake_case consistently, but most JS APIs send and receive camelCase. A new plug makes the translation when sending or receiving transparently.

Convert between snake_case and camelCase automatically.

---

lib/beacon/content.ex
lib/beacon/content/layout.ex
lib/beacon/content/page.ex
test/beacon/content_test.exs

The same pattern used on page variants, which is more effective since it only validates when necessary and not on every change.

Move layout and page template validation to context

---

CONTRIBUTING.md
dev.exs
guides/introduction/installation.md
lib/beacon/content.ex
lib/beacon/content/layout.ex
lib/beacon/loader/layout_module_loader.ex
lib/beacon/tailwind_compiler.ex
priv/repo/migrations/20230808180704_rename_layout_body_to_template.exs
priv/templates/install/seeds.exs
test/beacon/content_test.exs
test/beacon/loader_test.exs
test/beacon/tailwind_compiler_test.exs
test/support/fixtures.ex

Fixes https://github.com/BeaconCMS/beacon/issues/311
Adding a new migration to alter the column name in the table causes the older migration files to fail. Not sure what's the best way around this, so I just modified the previous migration files.

Rename layout.body to layout.template

---

dev.exs
lib/beacon/application.ex
lib/beacon/config.ex
lib/beacon/lifecycle/template.ex
lib/beacon/loader.ex
lib/beacon/loader/layout_module_loader.ex
lib/beacon/loader/page_module_loader.ex
lib/beacon/router.ex
lib/beacon/site_supervisor.ex
lib/beacon/template.ex
lib/beacon/template/heex.ex
lib/beacon_web/components/layouts.ex
lib/beacon_web/live/page_live.ex
test/beacon/lifecycle/template_test.exs
test/beacon/loader/page_module_loader_test.exs
test/beacon/loader_test.exs
test/beacon/router_test.exs
test/beacon_web/live/page_live_test.exs
test/beacon_web/publish_test.exs

The main change is getting rid of `Code.eval_quoted/3` which was necessary to render the pages since we were storing the template AST in ETS, but it was not scaling well.
The first design for page rendering was compiling a single module containing all page templates but it was causing a huge spike in memory utilization to compile 700+ pages, something around 4gb. The second design was then removing that module and storing all template AST in ETS, which consume only 2.6mb of data and the lookup is incredible fast but it doesn't scale to serve too many requests, especially sudden spikes, each `Code.eval_quoted/3` call increases CPU utilization up to 100% faster than we can afford. The third design (this PR) is a mix of both, it will compile a module per page containing the `render/1` …

Implement page compilation on demand

---

lib/beacon/lifecycle/template.ex
lib/beacon/loader.ex
lib/beacon/loader/page_module_loader.ex
lib/beacon/pub_sub.ex
test/beacon/lifecycle/template_test.exs
test/beacon/loader/page_module_loader_test.exs
test/beacon/loader_test.exs
test/beacon_web/live/page_live_test.exs

Reloading a layout will force all pages using that layout to be recompiled without a template which will be reloaded on demand as requests try to render such pages, since we can't just recompile all page modules at once. It won't change the page the user is visiting, only on the next request or after refreshing the page.

Reload layout

---

lib/beacon/content.ex
lib/beacon/lifecycle/template.ex
lib/beacon/loader.ex
lib/beacon/loader/layout_module_loader.ex
lib/beacon/loader/page_module_loader.ex
lib/beacon/site_supervisor.ex
lib/beacon_web/components/layouts.ex
test/beacon/lifecycle/template_test.exs
test/beacon/loader/page_module_loader_test.exs
test/beacon/loader_test.exs
test/beacon_web/live/page_live_test.exs
test/beacon_web/publish_test.exs

- Move the pubsub broadcast outside of the repo transaction since `Beacon.Loader` query the database to find the latest published page/layout.
- Revert `PageModuleLoader` as a simple module and let only `Loader` be a genserver so we have a single queue for loading resources since they depend on each other.
- Revert page template unloading, introduced at https://github.com/BeaconCMS/beacon/pull/335, since we require users to refresh the page to see the updated markup and the pubsub fix is all we need.

Fix publish process

---

guides/introduction/installation.md

The URL params will be passed with string keys, but the  line with `@beacon_path_params.blog_slug` is looking for an atom as the key, and so will fail with a KeyError, like so:
```
(KeyError) key :blog_slug not found in: %{"blog_slug" => "my_first_post"}
```
This took me a little while to figure out, so hopefully this will save someone some time, and come up when they google the error message.

Fix bug in seeds file listing on installation.md

---

priv/templates/install/seeds.exs

Hey @everyone.
I was just playing with the installer and I noticed a difference from the beacon_demo project and the default beacon project.
Whenever I run the seeds the url /blog/:blog_slug does not seem to work.
The reason I suspect is because the syntax used.
With the update using the syntax from inside the beacon_demo project the path seem to work.
Expected behavior:
/blog/:blog_slug should render page with matching path

Fix Template Beacon Seeds File syntax

---

lib/beacon/lifecycle/template.ex
lib/beacon/loader.ex
lib/beacon/loader/page_module_loader.ex
lib/beacon/media_library.ex
lib/beacon/router.ex
lib/beacon/tailwind_compiler.ex
lib/beacon/template.ex
test/beacon/tailwind_compiler_test.exs

Fix tailwind parser

---

lib/beacon/content.ex

1. Added support for offsetting `list_pages/2` which we'll need for pagination purposes
2. Added an extra function for counting the total amount or pages records we have (needed for determining the amount of pages in the navigation component)

Add offset support for listing pages and counting pages

---

lib/beacon/types/site.ex
lib/mix/tasks/install.ex
test/beacon/types/site_test.exs
test/mix/tasks/install_test.exs

Issue: https://github.com/BeaconCMS/beacon/issues/333

Issue 333 don't allow sites starting with beacon 

---

lib/beacon/content.ex
test/beacon/content_test.exs
test/test_helper.exs

Implemented in https://github.com/BeaconCMS/beacon/commit/62094e85ee59db598909b3df37a80e7d4ec82684 but the code was incorrectly removed during the Context API refactor

New Page - include default meta tags

---

guides/introduction/installation.md
lib/beacon/behaviors/helpers.ex

Hey guys
So I was just doing the manual steps on the installation guide and noticed while copy and pasting the seeds that there were double %% causing it to now work inside the iex. I also added an example on those seeds explicitly changing the value of <%= site %> to the name of the example provided:
(and I found a typo in one of the commits)
I have a question, the same thing happens on the seeds.exs, the double %%, is it a typo? Or it is a syntax that IDK about it?

Docs: Installation Guide Improve Manual Steps

---

lib/beacon/types/site.ex
lib/mix/tasks/install.ex
priv/templates/install/beacon_router_scope.ex
test/beacon/types/site_test.exs
test/mix/tasks/install_test.exs

https://github.com/BeaconCMS/beacon/issues/306

Feat: Route and Resource Loading Add --path to beacon.install generator

---

guides/deployment/multiple_domains_hosting.md

Issue: https://github.com/BeaconCMS/beacon/issues/95

Create doc/guide for multiple domains hosting with Beacon

---

lib/beacon_web/components/components.ex
test/beacon_web/components/components_test.exs

Issue: https://github.com/BeaconCMS/beacon/issues/357

Feat: Page Builder Featured Pages Component

---

lib/beacon/config.ex
lib/beacon/content.ex
lib/beacon/lifecycle/template.ex
lib/beacon/loader/component_module_loader.ex
lib/beacon/loader/layout_module_loader.ex
lib/beacon/loader/page_module_loader.ex
lib/beacon/router.ex
lib/beacon/tailwind_compiler.ex
lib/beacon/template/heex.ex
test/beacon/tailwind_compiler_test.exs
test/test_helper.exs

- Revert part of #376 to allow compiling CSS on app boot
- Change the `:load_template` lifecycle to only return the template binary so it doesn't compile it
Close #392

Fix CSS compiler

---

guides/introduction/installation.md
lib/beacon/loader/component_module_loader.ex
lib/beacon/loader/error_page_module_loader.ex
lib/beacon/loader/layout_module_loader.ex
lib/beacon/loader/page_module_loader.ex
lib/beacon_web.ex
lib/beacon_web/live/page_live.ex
mix.exs
test/beacon_web/live/page_live_test.exs
test/support/beacon.ex

I _think_ this resolves the issue reported here https://github.com/BeaconCMS/beacon/issues/403
All the tests are passing after removing the `import` and `use` of `Phoenix.HTML`.
I updated the tests to consume `input` and `button` from `BeaconWeb.CoreComponents`.
Not sure if I'm missing something important though!

Support phoenix html 4.x

---

README.md
dev.exs
guides/introduction/installation.md
lib/beacon/content.ex
lib/beacon/content/live_data.ex
lib/beacon/content/page.ex
lib/beacon/schema.ex
lib/beacon_web/live/page_live.ex
priv/templates/install/seeds.exs
test/beacon/content_test.exs
test/beacon/loader/data_source_module_loader_test.exs
test/beacon/loader/page_module_loader_test.exs
test/beacon/schema_test.exs
test/beacon_web/components/components_test.exs
test/beacon_web/live/page_live_test.exs
test/beacon_web/publish_test.exs

Close #395 
Follow the behavior defined by Phoenix - https://github.com/phoenixframework/phoenix/blob/ab3351a0f262b2870c3b59ebc04de41c6e607550/lib/phoenix/router/scope.ex#L113
That reduces some checks we had to do and fixes an issue with the Live Data editor in beacon_live_admin

Enforce path with a leading slash

---

.gitignore
dev.exs
lib/beacon/authorization.ex
lib/beacon/beacon.ex
lib/beacon/boot.ex
lib/beacon/config.ex
lib/beacon/pub_sub.ex
lib/beacon/registry.ex
lib/beacon/router_server.ex
lib/beacon/site_supervisor.ex
test/beacon/beacon_test.exs
test/beacon/config_test.exs
test/beacon/content_test.exs
test/beacon/registry_test.exs
test/support/beacon_web.ex
test/support/router.ex
test/test_helper.exs

Disabling site boot will skip the following steps:
- Loading default data
- Loading modules
- Broadcasting events
That's necessary to run tests without conflicts and to seed initial data.
Beacon.Repo and all the other necessary servers are started as usual.

Control site boot

---

lib/beacon/content.ex
test/beacon/content_test.exs

PageVariants and LiveDataAssigns are being validated on update, but not on create.  It might be that creation does not involve user inputted data so validation on create has not been necessary yet.  But we should probably add this anyway

Validate variants and live_data on create

---

lib/beacon/content.ex

Pages generated on schema v2 didn't store loaded variants

Fix loading published pages schema v2

---

dev.exs
guides/introduction/installation.md
lib/beacon/beacon.ex
lib/beacon/lifecycle/template.ex
lib/beacon/loader/components.ex
lib/beacon/loader/error_page.ex
lib/beacon/loader/layout.ex
lib/beacon/loader/live_data.ex
lib/beacon/loader/page.ex
lib/beacon/template.ex
lib/beacon_web.ex
lib/beacon_web/beacon_assigns.ex
lib/beacon_web/components/layouts.ex
lib/beacon_web/controllers/api/page_json.ex
lib/beacon_web/controllers/error_html.ex
lib/beacon_web/data_source.ex
lib/beacon_web/exceptions.ex
lib/beacon_web/live/page_live.ex
priv/templates/install/seeds.exs
test/beacon/loader/error_page_test.exs
test/beacon/tailwind_compiler_test.exs
test/beacon/template/heex/heex_decoder_test.exs
test/beacon/template/heex/json_encoder_test.exs
test/beacon/template/heex/tokenizer_test.exs
test/beacon/template/heex_test.exs
test/beacon_web/beacon_assigns_test.exs
test/beacon_web/controllers/error_html_test.exs
test/beacon_web/live/page_live_test.exs
test/beacon_web_test.exs
test/support/beacon_web.ex

Close #369 
- `@beacon` assign is a container for public and private assigns, including path params, query params, and others that used to be defined on its own assigns as `@beacon_*` or as `__{name}__` 
- `@beacon_live_data` is deprecated if favor of accessing those values from `assigns` directly, ie: `@name` instead of `@beacon_live_data[:name]`
- Add custom `assign` functions to warn and block assigning the `:beacon` key, those functions are called in event handlers and any exposed code block in the page editor

Introduce `@beacon` and deprecate `@beacon_*` assigns

---

README.md

This ensures users following along with the beacon_live_admin instructions use the qualified node name

Update node name in README.md to match beacon_live_admin

---

config/config.exs
lib/beacon/content.ex
lib/beacon/content/component.ex
lib/beacon/content/component_attr.ex
lib/beacon/content/component_slot.ex
lib/beacon/content/component_slot_attr.ex

- Move component_attr and slot_attr changeset validations to component.ex
- Add query to order Component preloads (`attrs` and `slots`) by name (if preloads are given)
- Add changeset validations - Unique name for ComponentAttr, ComponentSlot and ComponentSlotAttr

Validate ComponentAttr/SlotAttr Name

---

lib/beacon/authorization/policy.ex
lib/beacon/beacon.ex
lib/beacon/config.ex
lib/beacon/content.ex
lib/beacon/content/component_attr.ex
lib/beacon/content/component_slot.ex
lib/beacon/content/component_slot_attr.ex
lib/beacon/content/page.ex
lib/beacon/content/page/helper.ex
lib/beacon/media_library.ex
lib/beacon/migration.ex
lib/beacon/router.ex
lib/beacon/runtime_css.ex
lib/beacon/tailwind_compiler.ex
lib/beacon_web/beacon_assigns.ex
lib/errors.ex
mix.exs

* Adds some basic moduledoc to replace TODOs
* Group content functions which were missing group
* Move embedded schema Page.Helper into its own module so it can be undocumented
* Replace deprecated `groups_for_functions` with `groups_for_docs`
* Remove injected `child_spec` (from GenServer/Supervisor) from docs

Update content docs

---

guides/recipes/on_mount_handle_info_loop.md

After getting help in the beacon slack, I promised to add a guide for `on_mount` and `handle_info` within a given page.
The example is simple just adding a constantly updating clock.
Let me know if you have a better idea of how to show this feature and to let it shine.
Thanks!

add guide for on_mount and handle_info

---

.github/workflows/ci.yml
lib/beacon/content.ex
lib/beacon/content/component.ex
lib/beacon/content/component_slot.ex
lib/beacon/loader/components.ex
test/beacon/content_test.exs

Fixes the error `[error] failed to compile module Elixir.Beacon.Web.LiveRenderer.a0bcc01f27e792cd27ed89d15303a9da.Page94f2b1db-1900-4654-a402-986bcb0f27f9`
One of the built-in components were created incorrectly with an invalid slot opt which was causing the `Components` module to fail. This change validates attr opts and slot opts to avoid invalid state and also ignore invalid opts when loading the Components module.

Content/Component - validate attr opts and slot opts

---

lib/beacon/private.ex
lib/beacon/pub_sub.ex
lib/beacon/web/live/page_live.ex
test/beacon_web/live/page_live_test.exs
test/support/router.ex

Suppose the following routes:
```elixir
scope "/", host: "sitea.com" do
pipe_through [:browser]
beacon_site "/sitea", site: :site_a
end
scope "/", host: "siteb.com" do
pipe_through [:browser]
beacon_site "/siteb", site: :site_b
end
```
Given you're in any page of site_a and there's a link to another site such as http://siteb.com:4000/other
This change will allow Beacon to patch the contents of the page and display the /other page from site_b
That's very powerful because it allows to navigate between sites without requiring full refreshes. For instance LiveView does allow this kind of navigation too.
Note that patching to relative paths is not supported by LV and won't be supported by Beacon either. For eg a patch link to /other will raise.
Thanks to @APB9785 for the discussion on this …

Allow to patch (navigate patching the content) to another site

---

mix.exs

Due to a bug in `Image.open/1`

Skip `:vix` v0.31.0

---

guides/recipes/basic-page-authentication.md

This recipe describes how to create and implement your own plug for basic authentication on your app, using [`Plug.BasicAuth`](https://hexdocs.pm/plug/Plug.BasicAuth.html).

Add recipe for basic page authentication

---

dev.exs
lib/beacon/content.ex
lib/beacon/loader/routes.ex
lib/beacon/media_library/provider/repo.ex
lib/beacon/router.ex
lib/beacon/web/controllers/media_library_controller.ex
test/beacon/loader/routes_test.exs
test/beacon/media_library_test.exs
test/beacon_web/controllers/media_library_controller_test.exs
test/support/beacon_web.ex
test/support/router.ex

Close #642
Now it allows to use `beacon_site` inside aliased scopes and also doesn't expose the site name.

fix: serve media library assets inside aliased scopes

---

lib/beacon/beacon.ex
lib/beacon/boot.ex
lib/beacon/error_handler.ex
lib/beacon/loader.ex
lib/beacon/loader/components.ex
lib/beacon/loader/error_page.ex
lib/beacon/loader/layout.ex
lib/beacon/loader/page.ex
lib/beacon/loader/worker.ex
lib/beacon/router_server.ex
lib/beacon/test/fixtures.ex
lib/beacon/web/data_source.ex
lib/beacon/web/live/page_live.ex
test/beacon/content_test.exs
test/beacon/lifecycle/template_test.exs
test/beacon/loader/components_test.exs
test/beacon/loader/error_page_test.exs
test/beacon/loader/page_test.exs
test/beacon/loader/routes_test.exs
test/beacon/loader_test.exs
test/beacon/media_library_test.exs
test/beacon/router_server_test.exs
test/beacon_web/beacon_assigns_test.exs
test/beacon_web/controllers/media_library_controller_test.exs
test/beacon_web/data_source_test.exs
test/beacon_web/live/page_live_test.exs

This re-adds the Global locking mechanism via Registry, but with an extra feature to prevent crashes due to our Loader process of manually compiling dynamic modules which `import` other dynamic modules (which might not be loaded yet).
Now the Loader will force compilation of any `import` modules before compiling the module which does the importing

Global lock, Take 2

---

CHANGELOG.md
lib/beacon/boot.ex
lib/beacon/config.ex
lib/beacon/content.ex
test/beacon/content_test.exs

Adds feature to warm pages on Beacon Boot.  Configured via `Beacon.Config` `:page_warming`. Allowed options are:
* `{:shortest_paths, n}` - warms the `n` pages with the shortest paths (using database `LENGTH()` function)
* `{:specific_paths, list_of_path_strings}` - attempts to warm all pages with the provided paths.  skips if the page is unpublished
* `:none` - disables the page warming feature entirely

Page warming

---

CHANGELOG.md
lib/beacon/loader/page.ex
lib/beacon/web/beacon_assigns.ex
lib/beacon/web/controllers/api/page_json.ex
lib/beacon/web/data_source.ex
lib/beacon/web/live/page_live.ex
test/beacon_web/data_source_test.exs

This adds a `source` argument for building BeaconAssigns, particularly the `page_title`, which currently doesn't work for unpublished pages.
The `beacon_live_admin` visual editor goes through the JSON endpoint and often needs to build assigns for unpublished pages.  Therefore this endpoint will have the `:admin` source (default source is `:beacon`).
The `:admin` source requests will not do any Dynamic Module calling/loading (because this is not allowed for unpublished pages).  Instead, it will just do a database call.

allow admin source for beacon assigns in unpublished pages

---

lib/beacon/beacon.ex
lib/beacon/content/snippets/tag_helper.ex
lib/beacon/lifecycle/template.ex
lib/beacon/loader.ex
lib/beacon/loader/components.ex
lib/beacon/loader/page.ex
lib/beacon/loader/worker.ex
lib/beacon/media_library/provider/repo.ex
lib/beacon/router_server.ex
lib/beacon/template.ex
lib/beacon/web/components/layouts.ex
lib/beacon/web/controllers/api/page_json.ex
lib/beacon/web/controllers/error_html.ex
lib/beacon/web/data_source.ex
lib/beacon/web/live/page_live.ex
lib/errors.ex
test/beacon/loader_test.exs
test/beacon_web/controllers/media_library_controller_test.exs

Ensure Beacon's autoloader is enabled (Beacon.ErrorHandler) before trying to call a dynamic function in a module managed by Beacon (page module, components module, routes, etc)
We concentrate all calls into `Beacon.apply_mfa/5` so we have a single source to maintain and it will also spawn a `Loader` worker process to avoid leaking the `:error_handler` flag into the caller.

chore: isolate dynamic function calls

---

test/beacon/template/heex/heex_decoder_test.exs
test/beacon_web/live/page_live_test.exs

From LV patch notes:
> * Fix live_session not being enforced when patching to the same LiveView under a different route
this means we need to navigate instead of patch when moving between sites
also some renderings now use braces `{ }` instead of the previous HEEx interpolation `<%= %>` since we use that LiveView rendering engine under the hood

Update tests for LV 1.0 compatibility

---

lib/beacon/loader.ex
lib/beacon/loader/live_data.ex
test/beacon/loader/live_data_test.exs
test/beacon/loader_test.exs

Live Data are invoked with Beacon.Loader which would rescue and reraise causing the original error to be lost, but that should not happen for Live Data calls since users might raise custom errors.

fix: forward live data errors

---

lib/mix/tasks/beacon.gen.site.ex
lib/mix/tasks/beacon.install.ex
test/mix/tasks/gen_site_test.exs
test/mix/tasks/install_test.exs

```elixir
pipeline :beacon_admin do
plug Beacon.LiveAdmin.Plug
end
pipeline :beacon do
plug Beacon.Plug
end
scope "/" do
pipe_through [:browser, :beacon_admin]
beacon_live_admin "/admin"
end
scope "/", MyAppWeb do
pipe_through [:browser, :beacon]
beacon_site "/", site: :my_site
end
```

chore: add :beacon pipeline

---

lib/beacon/loader.ex

This is a fix for possible site instability after updating a Beacon Component via LiveAdmin
* Reports of 500 response across the entire site, after making an update to a Beacon Component
* Seems like the cause is existing templates `import`ing that Component module, which for some reason does not trigger `Beacon.ErrorHandler`
* If we find a culprit for ^ this line could be removed again, but for now it prevents the bug from occurring

Reload components module after updating

---

lib/beacon/router.ex
test/beacon/router_test.exs
test/support/live_views.ex
test/support/router.ex

Allow root paths / to coexist and start beacon sites even if there's a conflict to allow nested beacon pages as /:page to be served, even in the presence of another live / route.
This change will potentially cause more sites to be started but being to restrictive is a breaking change either, so we're partially reverting to v0.2 behavior.

fix: make Router.reachable/2 less strict

---

lib/beacon/plug.ex
lib/beacon/web/live/page_live.ex

If a page loads other assets which pass through the Beacon.Plug, those assets were re-rolling the page variant, which caused the live render to sometimes have a different variant than the dead render (especially when response time is slower).
This PR only allows the initial page request to roll a variant, all other requests passing through that Plug will leave the variant session data untouched.

Fix variant roll changing when fetching assets

---

lib/beacon/private.ex

Using LV 1.0.0 with Beacon will currently crash because the function was not added until 1.0.1

Prevent missing fn on LV 1.0.0

---

lib/beacon/router.ex
lib/beacon/template.ex
lib/beacon/web/beacon_assigns.ex
lib/beacon/web/controllers/api/page_json.ex
lib/beacon/web/data_source.ex
lib/beacon/web/live/page_live.ex
test/beacon_web/beacon_assigns_test.exs
test/beacon_web/data_source_test.exs

`Beacon.Content.get_page/2` fails since there's no page saved yet. This PR also simplified a few things:
- Simplify the build of a new `@beacon` assign
- Make the arguments more explicit
- Remove the `source` arg so callers don't need to be responsible for how the assign is built

fix: load visual editor on new pages

---

dev.exs
guides/general/troubleshooting.md
guides/upgrading/v0.4.0.md
lib/beacon/beacon.ex
lib/beacon/private.ex
lib/beacon/router.ex
lib/mix/tasks/beacon.gen.site.ex
test/mix/tasks/gen_site_test.exs

Start Beacon before Endpoint so requests are blocked until the host app is ready to accept them, otherwise we expose Beacon to race conditions causing blank pages and boot errors.

fix: crash recovery

---

lib/beacon/loader/worker.ex
lib/beacon/media_library/upload_metadata.ex
lib/beacon/test/fixtures.ex

So it doesn't introduce breaking changes and also doesn't require consumers/clients to pass it, unless they need to, since the default is `Node.self()`

fix: make `node` in `UploadMetadata.new` optional

---

dev.exs
lib/beacon/loader/routes.ex
lib/beacon/private.ex
lib/beacon/proxy_endpoint.ex
lib/beacon/router.ex
lib/beacon/runtime_css.ex
lib/beacon/web/controllers/robots_controller.ex
lib/beacon/web/controllers/sitemap_controller.ex
lib/beacon/web/sitemap/sitemap_index.xml.eex
lib/mix/tasks/beacon.gen.proxy_endpoint.ex
lib/mix/tasks/beacon.gen.site.ex
lib/mix/tasks/beacon.gen.tailwind_config.ex
test/beacon/loader/routes_test.exs
test/beacon/media_library_test.exs
test/beacon_web/controllers/robots_controller_test.exs
test/beacon_web/controllers/sitemap_controller_test.exs
test/mix/tasks/gen_site_test.exs
test/mix/tasks/gen_tailwind_config_test.exs
test/support/endpoint.ex
test/support/endpoint_b.ex
test/support/endpoint_site.ex
test/support/endpoints.ex
test/support/proxy_endpoint.ex

- Isolate each site on its own endpoint to avoid conflicts with static paths and other configs
- Use the Proxy Endpoint to generate public URL for sites
- Fix the URL in robots.txt and sitemap.xml (should use the exposed public scheme/port)
- Fix to use Beacon ErrorHTML 
- Update generators to always create the site endpoint and use it in configs
- (Breaking) asset_url -> css_config_url (needs to change admin as well)

feat: always generate site endpoints

---

lib/mix/tasks/beacon.gen.site.ex
lib/mix/tasks/beacon.gen.tailwind_config.ex
test/mix/tasks/gen_site_test.exs
test/mix/tasks/gen_tailwind_config_test.exs

esbuild config `:default` is no longer used and those watchers are not needed

fix: remove :watcher from site endpoint

---

lib/mix/tasks/beacon.gen.proxy_endpoint.ex
test/mix/tasks/gen_proxy_endpoint_test.exs
test/mix/tasks/gen_site_test.exs

Apps will crash on PubSub broadcast if this config value isn't set in the ProxyEndpoint

fix(`beacon.gen.proxy_endpoint`): configure ProxyEndpoint `:pubsub_server`

---

lib/mix/tasks/beacon.gen.site.ex

* Now overwrites site endpoint if it already exists, instead of failing the task (#764)
* Don't remove extra Beacon.Config the user may have set for the site in `runtime.exs` (#763)

fix(beacon.gen.site): don't fail on pre-existing endpoint module or remove extra beacon runtime config

---

lib/beacon/media_library.ex
lib/beacon/media_library/provider.ex
lib/beacon/media_library/provider/s3.ex
test/beacon/media_library_test.exs

- avoid crashing on invalid providers
- remove `media_path/2` since not all providers can return a path
- rename media_url -> url_for_asset to use same pattern as `url_for/1`
- make `url_for_asset/2` use the asset provider instead of generating a local URL
Follow-up of https://github.com/BeaconCMS/beacon/pull/774

chore: improve media library API

---

lib/beacon/proxy_endpoint.ex

Fix FunctionClauseError when host/port doesn't match

fix: check origin clause

---

lib/beacon/private.ex
lib/beacon/web/controllers/api/page_json.ex
test/beacon/private_test.exs
test/beacon_web/live/page_live_test.exs
test/support/routers.ex

Assigns defined in `beacon_site` `:on_mount` should display their actual values in the Visual Editor.

feat(visual editor): resolve on_mount assigns

---

lib/beacon/igniter.ex
lib/mix/tasks/beacon.gen.site.ex
test/mix/tasks/gen_site_test.exs

Fix https://github.com/BeaconCMS/beacon/issues/744
Since beacon_site adds a catch-all route `/*path` it should be placed after other routes to avoid conflicts.
Depends on https://github.com/ash-project/igniter/pull/251

fix: reduce beacon_site priority (mount after other routes)

---

lib/beacon/lifecycle/asset.ex
lib/beacon/media_library.ex
lib/beacon/media_library/provider.ex
lib/beacon/media_library/provider/repo.ex
lib/beacon/media_library/provider/s3.ex

It will allow users to customize a `soft_delete/1` callback that's used when `Beacon.MediaLibrary.soft_delete/1` gets called.
This feature is necessary to be able to programmatically delete stored assets where they are stored when utilizing custom provider modules for the media library's asset upload functionality.
[Previous PR ](https://github.com/BeaconCMS/beacon/pull/601)

adds customizable asset delete callbacks

---

lib/beacon/migrations/v001.ex
lib/beacon/migrations/v002.ex
lib/beacon/migrations/v003.ex
lib/beacon/schema.ex

Resolves issue #776
Hardcode the "inserted_at" and "updated_at" names for timestamps options in Ecto migrations and schemas. As Beacon is configured to use a host application's Ecto Repo, querying for those columns by their default names may fail if the host application defines custom column names (e.g. "created_at" in place of "inserted_at").

Hardcode "inserted_at" & "updated_at" in Ecto migrations & schemas.
